import Head from "next/head";
import { Inter } from "next/font/google";
import productsJson from "../../public/data/products.json";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import useFilters from "@/hooks/useFilters";
import { init } from "next/dist/compiled/@vercel/og/satori";
import { useContext, useEffect, useState } from "react";
import { Products } from "@/types/types";
import ProductsList from "@/components/ProductsList/ProductsList";
import Cart from "@/components/Cart/Cart";
import styles from "@/styles/global.module.css";
import { ThemeContext } from "@/contexts/ThemeContext/ThemeContext";
import Toggle from "@/components/Toggle/Toggle";
export const IS_DEVELOPMENT = process.env.NODE_ENV !== "production";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const initialState = productsJson.products;

  const [products] = useState<Products[]>(initialState);
  const { filterProducts } = useFilters();

  const filteredProducts = filterProducts(products);

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" />
      </Head>

      <Toggle />
      <Header />

      <Cart />
      <main>
        <ProductsList products={filteredProducts} />
      </main>
      {/* {IS_DEVELOPMENT && <Footer />} */}
    </>
  );
}
